import { Shop, SavedSearch, Find } from './types'

// Axbridge home: 51.2897, -2.8174

export const SHOPS: Shop[] = [
  {
    id: 1,
    name: 'Bristol Jewellery Company',
    address: '40 The Mall, Clifton Village',
    town: 'Bristol',
    county: 'Bristol',
    postcode: 'BS8 4DS',
    lat: 51.4567,
    lng: -2.6186,
    distance: 16,
    eras: ['Victorian', 'Edwardian', 'Art Deco', 'General'],
    type: 'specialist',
    website: 'https://bristoljewellerycompany.com',
    notes: 'Independent specialist, 35 years in the trade. Covers all precious metals and stones. Buys and sells.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: true,
  },
  {
    id: 2,
    name: 'Wells Antique Centre',
    address: 'The Old Corn Exchange, Market Place',
    town: 'Wells',
    county: 'Somerset',
    postcode: 'BA5 2RB',
    lat: 51.2094,
    lng: -2.6474,
    distance: 10,
    eras: ['Victorian', 'Georgian', 'Edwardian', 'General'],
    type: 'market',
    phone: '01749 672784',
    notes: 'Multi-dealer centre in a converted corn exchange. Strong jewellery section, good turnover.',
    openingHours: 'Mon–Sat 10am–5pm, Sun 11am–4pm',
    verified: true,
  },
  {
    id: 3,
    name: 'Glastonbury Antiques Centre',
    address: '2a Magdalene Street',
    town: 'Glastonbury',
    county: 'Somerset',
    postcode: 'BA6 9EW',
    lat: 51.1431,
    lng: -2.7162,
    distance: 11,
    eras: ['Victorian', 'Art Nouveau', 'General'],
    type: 'market',
    phone: '01458 834386',
    notes: 'Eclectic mix. Good for unusual Victorian and Arts & Crafts pieces.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: false,
  },
  {
    id: 4,
    name: 'Holts Jewellery',
    address: 'Georgian Townhouse, Bath City Centre',
    town: 'Bath',
    county: 'Somerset',
    postcode: 'BA1 1',
    lat: 51.3818,
    lng: -2.3595,
    distance: 22,
    eras: ['Victorian', 'Art Nouveau', 'Edwardian', 'Art Deco'],
    type: 'specialist',
    email: 'email@holtsjewellery.co.uk',
    website: 'https://www.holtsjewellery.co.uk',
    notes: 'Appointment-based showroom in a Georgian townhouse. Melissa hand-picks every piece. Virtual appointments available.',
    openingHours: 'By appointment',
    verified: true,
  },
  {
    id: 5,
    name: 'Bartlett Street Antiques Centre',
    address: '8 Bartlett Street',
    town: 'Bath',
    county: 'Somerset',
    postcode: 'BA1 2QZ',
    lat: 51.3824,
    lng: -2.3596,
    distance: 22,
    eras: ['Georgian', 'Victorian', 'Regency', 'Edwardian'],
    type: 'market',
    phone: '01225 443536',
    website: 'https://www.bartlettstreetantiquescentre.com',
    notes: '5th decade running. Working goldsmith on site. Simon Millard FGA (01225 469785) and M.I. Clarke Jewellery (01225 469570) are the jewellery specialists.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: true,
  },
  {
    id: 6,
    name: 'Nigel Dando Fine Jewellers',
    address: 'Pulteney Bridge',
    town: 'Bath',
    county: 'Somerset',
    postcode: 'BA2 4AX',
    lat: 51.3807,
    lng: -2.3580,
    distance: 22,
    eras: ['Victorian', 'Edwardian', 'Art Deco', 'General'],
    type: 'specialist',
    website: 'https://nigeldando.co.uk',
    notes: '50+ years experience. Stock changes extremely frequently. Pulteney Bridge location is iconic. Worth calling ahead.',
    openingHours: 'Mon–Sat 9:30am–5:30pm',
    verified: true,
  },
  {
    id: 7,
    name: 'Charles Hart Jewellers (Vintage Tom)',
    address: 'Frome',
    town: 'Frome',
    county: 'Somerset',
    postcode: 'BA11',
    lat: 51.2295,
    lng: -2.3196,
    distance: 18,
    eras: ['Georgian', 'Victorian', 'Edwardian', 'Art Deco', 'Art Nouveau'],
    type: 'specialist',
    phone: '01373 462089',
    website: 'https://vintagetom.co.uk',
    notes: 'Trading for 200+ years. NAG members. Also sells via eBay. Call between 9:30am–4:30pm GMT. Excellent for all eras.',
    openingHours: 'Mon–Sat 9:30am–4:30pm',
    verified: true,
  },
  {
    id: 8,
    name: 'Taunton Antiques Market',
    address: '27 Silver Street',
    town: 'Taunton',
    county: 'Somerset',
    postcode: 'TA1 3DH',
    lat: 51.0153,
    lng: -3.1014,
    distance: 21,
    eras: ['Victorian', 'Edwardian', 'General'],
    type: 'market',
    phone: '01823 289327',
    notes: 'Town centre market. Good regular turnover. Worth visiting monthly.',
    openingHours: 'Mon–Sat 9am–5pm',
    verified: false,
  },
  {
    id: 9,
    name: 'Clifton Antiques Market',
    address: '26 The Mall',
    town: 'Bristol',
    county: 'Bristol',
    postcode: 'BS8 4JG',
    lat: 51.4565,
    lng: -2.6190,
    distance: 16,
    eras: ['Victorian', 'Art Deco', 'Edwardian'],
    type: 'market',
    phone: '0117 974 1627',
    notes: 'Premium Clifton Village market. Good Art Deco and Edwardian pieces.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: true,
  },
  {
    id: 10,
    name: 'Great Western Antique Centre',
    address: 'Bartlett Street',
    town: 'Bath',
    county: 'Somerset',
    postcode: 'BA1 2QZ',
    lat: 51.3822,
    lng: -2.3600,
    distance: 22,
    eras: ['Victorian', 'Georgian', 'Art Deco', 'Edwardian', 'General'],
    type: 'market',
    notes: '250+ dealers across multiple floors. Large dedicated jewellery section. Strong turnover.',
    openingHours: 'Mon–Sat 10am–5pm, Sun 11am–4pm',
    verified: false,
  },
  {
    id: 11,
    name: 'Malthouse Antiques',
    address: 'Market Place',
    town: 'Tetbury',
    county: 'Gloucestershire',
    postcode: 'GL8 8DD',
    lat: 51.6397,
    lng: -2.1595,
    distance: 35,
    eras: ['Georgian', 'Victorian', 'Regency'],
    type: 'specialist',
    notes: 'Cotswolds specialist. Estate jewellery. Good Georgian.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: false,
  },
  {
    id: 12,
    name: 'Cirencester Antique Market',
    address: 'The Corn Hall, Market Place',
    town: 'Cirencester',
    county: 'Gloucestershire',
    postcode: 'GL7 2NY',
    lat: 51.7196,
    lng: -1.9672,
    distance: 38,
    eras: ['Georgian', 'Victorian', 'Edwardian'],
    type: 'market',
    phone: '01285 644542',
    notes: 'Cotswolds dealer network. Strong Georgian and Victorian. Regular market days.',
    openingHours: 'Mon–Sat 9am–5pm',
    verified: false,
  },
  {
    id: 13,
    name: 'Exeter Antiques Centre',
    address: 'The Quay',
    town: 'Exeter',
    county: 'Devon',
    postcode: 'EX2 4AN',
    lat: 50.7184,
    lng: -3.5345,
    distance: 52,
    eras: ['Victorian', 'Edwardian', 'Art Deco'],
    type: 'market',
    notes: 'Regional hub on the quayside. Strong silver section. Good Art Deco.',
    openingHours: 'Mon–Sun 10am–5pm',
    verified: false,
  },
  {
    id: 14,
    name: 'Cheltenham Antiques Market',
    address: 'Suffolk Road',
    town: 'Cheltenham',
    county: 'Gloucestershire',
    postcode: 'GL50 2AQ',
    lat: 51.8994,
    lng: -2.0783,
    distance: 56,
    eras: ['Georgian', 'Victorian', 'Art Deco', 'Regency'],
    type: 'market',
    phone: '01242 529812',
    notes: 'High-end Regency and Georgian pieces reflecting the town\'s heritage.',
    openingHours: 'Mon–Sat 9:30am–5pm',
    verified: false,
  },
  {
    id: 15,
    name: 'Oxford Antiques and Collectors Centre',
    address: '26 Park End Street',
    town: 'Oxford',
    county: 'Oxfordshire',
    postcode: 'OX1 1HU',
    lat: 51.7520,
    lng: -1.2630,
    distance: 68,
    eras: ['Georgian', 'Victorian', 'Art Deco', 'Modern'],
    type: 'market',
    notes: 'Large multi-dealer centre. Mix of academic and decorative pieces. Covered Market also worth visiting.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: false,
  },
  {
    id: 16,
    name: "Gray's Antique Market",
    address: '58 Davies Street, Mayfair',
    town: 'London',
    county: 'London',
    postcode: 'W1K 5LP',
    lat: 51.5120,
    lng: -0.1496,
    distance: 136,
    eras: ['Georgian', 'Victorian', 'Art Deco', 'Edwardian', 'Art Nouveau', 'Modern'],
    type: 'market',
    phone: '020 7629 7034',
    website: 'https://www.graysantiques.com',
    notes: 'Premier London antique market. 200+ specialist dealers. Charlotte Sayers (Stand 313-315) is exceptional for Stuart, Georgian, Victorian and Edwardian. Deco & Vintage Ltd (Stand 324) for valuations.',
    openingHours: 'Mon–Fri 10am–6pm',
    verified: true,
  },
  {
    id: 17,
    name: 'The Antique Jewellery Company',
    address: 'AJC Townhouse, Mayfair',
    town: 'London',
    county: 'London',
    postcode: 'W1',
    lat: 51.5104,
    lng: -0.1497,
    distance: 136,
    eras: ['Georgian', 'Victorian', 'Edwardian', 'Art Deco', 'Art Nouveau'],
    type: 'specialist',
    website: 'https://www.antiquejewellerycompany.com',
    notes: 'Founded by Olly. 45+ years. One of London\'s best-kept secrets. Appointment-based townhouse. Exceptional provenance.',
    openingHours: 'By appointment',
    verified: true,
  },
  {
    id: 18,
    name: 'Berganza',
    address: 'Hatton Garden',
    town: 'London',
    county: 'London',
    postcode: 'EC1N 8AA',
    lat: 51.5186,
    lng: -0.1085,
    distance: 135,
    eras: ['Georgian', 'Victorian', 'Edwardian', 'Art Deco'],
    type: 'specialist',
    website: 'https://www.berganza.com',
    notes: '70+ years in the trade. One of the finest collections in the world. Exceptional Victorian and Edwardian.',
    openingHours: 'Mon–Fri 10am–5:30pm, Sat 10am–4pm',
    verified: true,
  },
  {
    id: 19,
    name: "Alfies Antique Market",
    address: '13–25 Church Street, Marylebone',
    town: 'London',
    county: 'London',
    postcode: 'NW8 8DT',
    lat: 51.5245,
    lng: -0.1622,
    distance: 136,
    eras: ['Art Deco', 'Edwardian', 'Art Nouveau', 'Modern'],
    type: 'market',
    phone: '020 7723 6066',
    website: 'https://www.alfiesantiques.com',
    notes: 'Strong 20th C. jewellery floor. Good Art Deco and Arts & Crafts. Rooftop café.',
    openingHours: 'Tue–Sat 10am–6pm',
    verified: true,
  },
  {
    id: 20,
    name: 'Portobello Road Market',
    address: 'Portobello Road, Notting Hill',
    town: 'London',
    county: 'London',
    postcode: 'W11 2QB',
    lat: 51.5172,
    lng: -0.2042,
    distance: 137,
    eras: ['Victorian', 'Edwardian', 'Art Deco', 'General'],
    type: 'market',
    notes: 'Saturday only, 7am–3pm. Volume play — patience rewarded. Go early. Hundreds of dealers.',
    openingHours: 'Saturday only, 7am–3pm',
    verified: true,
  },
  {
    id: 21,
    name: 'Camden Passage',
    address: 'Camden Passage, Islington',
    town: 'London',
    county: 'London',
    postcode: 'N1 8EA',
    lat: 51.5365,
    lng: -0.1041,
    distance: 138,
    eras: ['Victorian', 'Georgian', 'Art Deco', 'Art Nouveau'],
    type: 'market',
    notes: 'Wednesday 8am–6pm and Saturday 8am–6pm. Excellent for Georgian and Art Nouveau. Multiple specialist dealers.',
    openingHours: 'Wed & Sat 8am–6pm',
    verified: true,
  },
  {
    id: 22,
    name: 'Bermondsey Antique Market',
    address: 'Bermondsey Square',
    town: 'London',
    county: 'London',
    postcode: 'SE1 3UN',
    lat: 51.4984,
    lng: -0.0721,
    distance: 137,
    eras: ['Georgian', 'Victorian', 'General'],
    type: 'market',
    notes: 'Friday 6am–2pm only. Serious trade market. Old "bona fide" rules apply. Go at dawn for the best pieces.',
    openingHours: 'Friday 6am–2pm only',
    verified: true,
  },
  {
    id: 23,
    name: 'Brighton Lanes Antique Market',
    address: 'The Lanes',
    town: 'Brighton',
    county: 'East Sussex',
    postcode: 'BN1 1HH',
    lat: 50.8195,
    lng: -0.1372,
    distance: 114,
    eras: ['Victorian', 'Art Deco', 'Edwardian', 'Art Nouveau'],
    type: 'market',
    notes: 'Dense cluster of antique jewellery dealers in The Lanes. Worth a day trip. Multiple specialists.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: false,
  },
  {
    id: 24,
    name: 'Birmingham Jewellery Quarter',
    address: 'Vyse Street & Frederick Street',
    town: 'Birmingham',
    county: 'West Midlands',
    postcode: 'B18 6HA',
    lat: 52.4883,
    lng: -1.9141,
    distance: 101,
    eras: ['Victorian', 'Edwardian', 'Modern'],
    type: 'specialist',
    notes: 'Manufacturing heritage district. Multiple dealers and workshops. Strong for estate pieces and repairs.',
    openingHours: 'Mon–Sat 9am–5pm',
    verified: false,
  },
  {
    id: 25,
    name: 'Butter Lane Antiques',
    address: 'Manchester',
    town: 'Manchester',
    county: 'Greater Manchester',
    postcode: 'M1',
    lat: 53.4808,
    lng: -2.2426,
    distance: 165,
    eras: ['Victorian', 'Art Deco', 'Art Nouveau', 'General'],
    type: 'specialist',
    website: 'https://www.butterlaneantiques.com',
    notes: 'Specialist in English antique jewellery and curiosities. Online and in-person.',
    verified: true,
  },
  {
    id: 26,
    name: 'Wharfedale Antiques',
    address: 'Ilkley',
    town: 'Ilkley',
    county: 'Yorkshire',
    postcode: 'LS29',
    lat: 53.9250,
    lng: -1.8309,
    distance: 195,
    eras: ['Victorian', 'Georgian', 'Edwardian', 'Art Deco'],
    type: 'specialist',
    website: 'https://www.wharfedaleantiques.com',
    notes: 'Family-run, Nicholsons Jewellers. Strong Yorkshire dealer network. XRF tested pieces.',
    verified: true,
  },
  {
    id: 27,
    name: 'York Antique Centre',
    address: '2 Lendal',
    town: 'York',
    county: 'Yorkshire',
    postcode: 'YO1 8AA',
    lat: 53.9590,
    lng: -1.0815,
    distance: 196,
    eras: ['Victorian', 'Georgian', 'Edwardian'],
    type: 'market',
    notes: 'Strong Northern dealer network. Good Victorian silver and jewellery.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: false,
  },
  {
    id: 28,
    name: 'Edinburgh Antique Dealers',
    address: 'Grassmarket & Victoria Street',
    town: 'Edinburgh',
    county: 'Edinburgh',
    postcode: 'EH1 2JR',
    lat: 55.9477,
    lng: -3.1930,
    distance: 312,
    eras: ['Georgian', 'Victorian', 'Scottish'],
    type: 'specialist',
    notes: 'Quality Georgian and Scottish jewellery. Multiple specialists on Grassmarket and Victoria Street. Worth a dedicated trip.',
    openingHours: 'Mon–Sat 10am–5pm',
    verified: false,
  },
]

export const SEARCHES: SavedSearch[] = [
  {
    id: 1,
    name: 'Victorian seed pearl',
    keywords: ['seed pearl brooch', 'seed pearl necklace', 'seed pearl ring victorian', 'seed pearl and gold'],
    platforms: ['eBay'],
    minPrice: 20,
    maxPrice: 300,
    active: true,
    lastRun: '2h ago',
    resultsToday: 4,
  },
  {
    id: 2,
    name: 'Georgian rings',
    keywords: ['georgian ring gold', 'mourning ring 18th century', 'posy ring antique', 'georgian gold ring'],
    platforms: ['eBay', 'Etsy'],
    minPrice: 50,
    maxPrice: 800,
    active: true,
    lastRun: '2h ago',
    resultsToday: 2,
  },
  {
    id: 3,
    name: 'Art Deco paste',
    keywords: ['art deco paste necklace', 'art deco paste brooch', 'art deco rhinestone silver', 'art deco marcasite'],
    platforms: ['eBay', 'Etsy'],
    minPrice: 15,
    maxPrice: 250,
    active: true,
    lastRun: '2h ago',
    resultsToday: 3,
  },
  {
    id: 4,
    name: 'Edwardian silver',
    keywords: ['edwardian silver brooch', 'edwardian silver pendant', 'edwardian silver bar pin'],
    platforms: ['eBay'],
    minPrice: 30,
    maxPrice: 400,
    active: true,
    lastRun: '4h ago',
    resultsToday: 1,
  },
  {
    id: 5,
    name: 'Victorian coral and gold',
    keywords: ['victorian coral brooch', 'antique coral gold', 'carved coral jewellery antique'],
    platforms: ['eBay', 'Etsy'],
    minPrice: 50,
    maxPrice: 600,
    active: false,
    lastRun: 'Yesterday',
    resultsToday: 0,
  },
  {
    id: 6,
    name: 'Turquoise antique',
    keywords: ['victorian turquoise ring', 'antique turquoise and pearl', 'turquoise forget-me-not'],
    platforms: ['eBay'],
    minPrice: 30,
    maxPrice: 350,
    active: true,
    lastRun: '2h ago',
    resultsToday: 2,
  },
  {
    id: 7,
    name: 'Mourning jewellery',
    keywords: ['victorian mourning brooch', 'jet brooch victorian', 'hair locket mourning', 'whitby jet'],
    platforms: ['eBay', 'Etsy'],
    minPrice: 25,
    maxPrice: 500,
    active: false,
    lastRun: '3 days ago',
    resultsToday: 0,
  },
  {
    id: 8,
    name: 'Enamel and gold',
    keywords: ['victorian enamel brooch gold', 'guilloché enamel antique', 'georgian enamel locket', 'antique enamel pendant'],
    platforms: ['eBay', 'Etsy'],
    minPrice: 40,
    maxPrice: 600,
    active: true,
    lastRun: '3h ago',
    resultsToday: 1,
  },
]

// Real antique jewellery images from Unsplash
export const FINDS: Find[] = [
  {
    id: 1,
    title: 'Victorian seed pearl and 9ct gold bar brooch',
    price: 85,
    platform: 'eBay',
    era: 'Victorian',
    status: 'New',
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80',
    foundAt: '2h ago',
    searchName: 'Victorian seed pearl',
    description: 'Beautiful 9ct gold bar brooch set with tiny seed pearls. Intact pin mechanism. Slight tarnish to gold, easily polished.',
    seller: 'antiquejewels_uk',
    condition: 'Good',
    interestScore: 88,
    interestReason: 'Seed pearl Victorian pieces consistently saved. Price well within range.',
  },
  {
    id: 2,
    title: 'Georgian garnet and gilt mourning ring c.1820',
    price: 320,
    platform: 'eBay',
    era: 'Georgian',
    status: 'Watching',
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80',
    foundAt: '4h ago',
    searchName: 'Georgian rings',
    description: 'Gold mourning ring with hair compartment to the interior. Garnet cabochon setting. Inscription visible on inner band.',
    seller: 'fineantiquesjewels',
    condition: 'Very Good',
    interestScore: 91,
    interestReason: 'Georgian mourning rings are a consistent pattern. Strong match.',
  },
  {
    id: 3,
    title: 'Art Deco paste and silver necklace',
    price: 145,
    platform: 'Etsy',
    era: 'Art Deco',
    status: 'Saved',
    imageUrl: 'https://images.unsplash.com/photo-1573408301185-9519f94f8d10?w=600&q=80',
    foundAt: '5h ago',
    searchName: 'Art Deco paste',
    description: 'Sterling silver Art Deco necklace with open-back paste stones. Geometric form. Good condition, one stone very slightly loose.',
    seller: 'decovintageuk',
    condition: 'Good',
    interestScore: 79,
    interestReason: 'Art Deco paste is a regular save. Price matches typical saves.',
  },
  {
    id: 4,
    title: 'Edwardian sapphire and diamond bar pin 15ct gold',
    price: 195,
    platform: 'eBay',
    era: 'Edwardian',
    status: 'New',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80',
    foundAt: '6h ago',
    searchName: 'Edwardian silver',
    description: 'Delicate 15ct gold bar pin set with old-cut diamonds and Ceylon sapphires. Original pin intact. Minor surface wear to gold.',
    seller: 'edwardianfinery',
    condition: 'Good',
    interestScore: 85,
    interestReason: 'Edwardian fine jewellery at this price point consistently gets saved.',
  },
  {
    id: 5,
    title: 'Victorian turquoise and pearl forget-me-not bangle',
    price: 260,
    platform: 'eBay',
    era: 'Victorian',
    status: 'Watching',
    imageUrl: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&q=80',
    foundAt: 'Yesterday',
    searchName: 'Turquoise antique',
    description: 'Gold bangle with applied turquoise forget-me-not flower cluster. 9ct gold. One small stone replacement but well-matched.',
    seller: 'victorianhoard',
    condition: 'Fair',
    interestScore: 72,
    interestReason: 'Turquoise Victorian pieces frequently saved. Condition noted as fair.',
  },
  {
    id: 6,
    title: 'Georgian paste rivière necklace, c.1800',
    price: 480,
    platform: 'Etsy',
    era: 'Georgian',
    status: 'Saved',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80',
    foundAt: '2 days',
    searchName: 'Georgian rings',
    description: 'Silver-topped gold rivière necklace set with graduated white paste stones in closed-back silver settings. 17 stones, all original.',
    seller: 'georgianjewelryco',
    condition: 'Very Good',
    interestScore: 94,
    interestReason: 'Georgian paste rivières are rare. Highest match in current profile.',
  },
  {
    id: 7,
    title: 'Edwardian 15ct gold and peridot pendant',
    price: 175,
    platform: 'eBay',
    era: 'Edwardian',
    status: 'Pass',
    imageUrl: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&q=80',
    foundAt: '2 days',
    searchName: 'Edwardian silver',
    description: 'Pendant with oval peridot and seed pearl surround. Fine trace chain included. Slight bend to bail.',
    seller: 'antiquejewellerysale',
    condition: 'Good',
    interestScore: 44,
    interestReason: 'Peridot pieces rarely saved. Price reasonable but low match overall.',
  },
  {
    id: 8,
    title: 'Art Deco marcasite and onyx earrings, silver',
    price: 55,
    platform: 'Etsy',
    era: 'Art Deco',
    status: 'New',
    imageUrl: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&q=80',
    foundAt: '3 days',
    searchName: 'Art Deco paste',
    description: 'Pair of sterling silver drop earrings with marcasite and black onyx in geometric Art Deco form. Screw-back fittings.',
    seller: 'decoadornments',
    condition: 'Excellent',
    interestScore: 81,
    interestReason: 'Art Deco geometric pieces at low price points are frequently saved.',
  },
  {
    id: 9,
    title: 'Victorian coral and gold spray brooch, c.1870',
    price: 210,
    platform: 'eBay',
    era: 'Victorian',
    status: 'Watching',
    imageUrl: 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600&q=80',
    foundAt: '3 days',
    searchName: 'Victorian coral and gold',
    description: 'Three-branch coral spray brooch in 9ct yellow gold. Natural salmon coral. One branch with very minor chip at tip.',
    seller: 'victoriangoldsmith',
    condition: 'Good',
    interestScore: 76,
    interestReason: 'Victorian coral pieces watch well. Minor condition note warrants caution.',
  },
  {
    id: 10,
    title: 'Georgian gold and guilloché enamel locket',
    price: 390,
    platform: 'eBay',
    era: 'Georgian',
    status: 'Saved',
    imageUrl: 'https://images.unsplash.com/photo-1515516969-d4008cc6241a?w=600&q=80',
    foundAt: '4 days',
    searchName: 'Enamel and gold',
    description: 'Oval locket with pale blue guilloché enamel to the front. Interior with two compartments and lock of hair. 18ct gold.',
    seller: 'regencyrelics',
    condition: 'Very Good',
    interestScore: 96,
    interestReason: 'Georgian enamel lockets are the strongest match in profile. Exceptional piece.',
  },
  {
    id: 11,
    title: 'Victorian jet and gold mourning brooch',
    price: 95,
    platform: 'eBay',
    era: 'Victorian',
    status: 'New',
    imageUrl: 'https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=600&q=80',
    foundAt: '5 days',
    searchName: 'Mourning jewellery',
    description: 'Carved Whitby jet brooch in oval form with central relief carving. Gold-filled pin fitting. All original.',
    seller: 'yorkshireantiques',
    condition: 'Very Good',
    interestScore: 68,
    interestReason: 'Mourning jewellery less frequently saved but strong craftsmanship here.',
  },
  {
    id: 12,
    title: 'Edwardian platinum and diamond half-hoop ring',
    price: 450,
    platform: 'Gray\'s Antique',
    era: 'Edwardian',
    status: 'New',
    imageUrl: 'https://images.unsplash.com/photo-1544376798-89aa6b0de8f9?w=600&q=80',
    foundAt: '5 days',
    searchName: 'Edwardian silver',
    description: 'Five-stone old-cut diamond ring in platinum millegrain setting. Total approx 0.75ct. Slight size adjustment needed.',
    seller: "Gray's Stand 313",
    condition: 'Excellent',
    interestScore: 87,
    interestReason: 'Diamond Edwardian rings at this price are strong matches. Platform suggests quality.',
  },
]
